let API_HOST = "http://huihuang.com/food/all";
let DEBUG = true;//切换数据入口
var Mock = require('mock.js')
function ajax(data = '', fn, method = "get", header = {}) {
    if (!DEBUG) {
        wx.request({
            url: config.API_HOST + data,
            method: method ? method : 'get',
            data: {},
            header: header ? header : { "Content-Type": "application/json" },
            success: function (res) {
                fn(res);
            }
        });
    } else {
        // 模拟数据
        var res = Mock.mock({
            // 'error_code': '',
            // 'error_msg': '',
            // 'data|10': [{
            //     'id|+1': 1,
            //     'img': "@image('200x100', '#4A7BF7','#fff','pic')",
            //     'title': '@ctitle(3,8)',
            //     'city': "@county(true)",
            //     'stock_num': '@integer(0,100)',//库存数量  
            //     'marketing_start': '@datetime()',
            //     'marketing_stop': '@now()',
            //     'price': '@integer(100,2000)',//现价，单位：分  
            //     'original_price': '@integer(100,3000)'
            // }]  
            menuArr: [{
              id: 1,
              name: '三拼饭(先选几拼再选菜)',
              sale: '20000',
              num: 0,
              price: 11,
              pic: '../pics/sanping.png',
              isVip: false,
              vipPrice: 0,
              notVip: true,
              isChoseType: true,
              isAddShopCar: false,
              isDelShopCar: false,
              isShowZero: false,
              spicy: '辣',
              notSpicy: '不辣',
              count: 0
            },
            {
              id: 2,
              name: '四拼饭(先选几拼再选菜)',
              sale: '2603',
              price: 13,
              num: 0,
              pic: '../pics/siping.png',
              isVip: false,
              vipPrice: 0,
              notVip: true,
              isChoseType: true,
              isAddShopCar: false,
              isDelShopCar: false,
              isShowZero: false,
              spicy: '辣',
              notSpicy: '不辣',
              count: 0
            },
            {
              id: 3,
              name: '卤水肉卷',
              sale: '570',
              num: 0,
              price: 0,
              pic: '../pics/lushuiroujuan.png',
              isVip: true,
              vipPrice: 0,
              notVip: false,
              isChoseType: false,
              isAddShopCar: true,
              isDelShopCar: true,
              isShowZero: false
            },
            {
              id: 4,
              name: '手撕包菜',
              sale: '368',
              num: 0,
              price: 0,
              pic: '../pics/shousibaocai.png',
              isVip: true,
              vipPrice: 0,
              notVip: false,
              isChoseType: false,
              isAddShopCar: true,
              isDelShopCar: true,
              isShowZero: false
            },
            {
              id: 5,
              name: '红烧肉',
              sale: '3216',
              num: 0,
              price: 0,
              pic: '../pics/hongshaorou.png',
              isVip: true,
              vipPrice: 0,
              notVip: false,
              isChoseType: false,
              isAddShopCar: true,
              isDelShopCar: true,
              isShowZero: false
            },
            {
              id: 6,
              name: '土豆牛肉',
              sale: '3854',
              num: 0,
              price: 0,
              pic: '../pics/tudouniurou.png',
              isVip: false,
              vipPrice: 0,
              notVip: true,
              isChoseType: false,
              isAddShopCar: true,
              isDelShopCar: true,
              isShowZero: false
            },
            {
              id: 7,
              name: '青瓜炒肉',
              sale: '1351',
              num: 0,
              price: 0,
              pic: '../pics/tudouniurou.png',
              isVip: false,
              vipPrice: 0,
              notVip: true,
              isChoseType: false,
              isAddShopCar: true,
              isDelShopCar: true,
              isShowZero: false
            },
            {
              id: 8,
              name: '土豆肉丝',
              sale: '2061',
              num: 0,
              price: 0,
              pic: '../pics/tudouniurou.png',
              isVip: false,
              vipPrice: 0,
              notVip: true,
              isChoseType: false,
              isAddShopCar: true,
              isDelShopCar: true,
              isShowZero: false
            },
            {
              id: 9,
              name: '番茄炒蛋',
              sale: '3383',
              num: 0,
              price: 0,
              pic: '../pics/tudouniurou.png',
              isVip: false,
              vipPrice: 0,
              notVip: true,
              isChoseType: false,
              isAddShopCar: true,
              isDelShopCar: true,
              isShowZero: false
            },
            {
              id: 10,
              name: '青椒牛肉',
              sale: '2929',
              num: 0,
              price: 0,
              pic: '../pics/tudouniurou.png',
              isVip: false,
              vipPrice: 0,
              notVip: true,
              isChoseType: false,
              isAddShopCar: true,
              isDelShopCar: true,
              isShowZero: false
            },
            {
              id: 11,
              name: '西兰花炒肉',
              sale: '3622',
              num: 0,
              price: 0,
              pic: '../pics/xilanhuachaorou.png',
              isVip: false,
              vipPrice: 0,
              notVip: true,
              isChoseType: false,
              isAddShopCar: true,
              isDelShopCar: true,
              isShowZero: false
            },
            {
              id: 12,
              name: '青瓜炒肉',
              sale: '681',
              num: 0,
              price: 0,
              pic: '../pics/xilanhuachaorou.png',
              isVip: false,
              vipPrice: 0,
              notVip: true,
              isChoseType: false,
              isAddShopCar: true,
              isDelShopCar: true,
              isShowZero: false
            },
            {
              id: 13,
              name: '榨菜肉丝',
              sale: '1452',
              num: 0,
              price: 0,
              pic: '../pics/taocan.png',
              isVip: false,
              vipPrice: 0,
              notVip: true,
              isChoseType: false,
              isAddShopCar: true,
              isDelShopCar: true,
              isShowZero: false
            },
            {
              id: 14,
              name: '苦瓜炒肉',
              sale: '2179',
              num: 0,
              price: 0,
              pic: '../pics/xilanhuachaorou.png',
              isVip: false,
              vipPrice: 0,
              notVip: true,
              isChoseType: false,
              isAddShopCar: true,
              isDelShopCar: true,
              isShowZero: false
            },
            {
              id: 15,
              name: '红烧茄子',
              sale: '4118',
              num: 0,
              price: 0,
              pic: '../pics/taocan.png',
              isVip: false,
              vipPrice: 0,
              notVip: true,
              isChoseType: false,
              isAddShopCar: true,
              isDelShopCar: true,
              isShowZero: false
            },
            {
              id: 16,
              name: '荷包蛋',
              sale: '3892',
              num: 0,
              price: 0,
              pic: '../pics/xilanhuachaorou.png',
              isVip: false,
              vipPrice: 0,
              notVip: true,
              isChoseType: false,
              isAddShopCar: true,
              isDelShopCar: true,
              isShowZero: false
            },
            {
              id: 17,
              name: '辣子鸡',
              sale: '4521',
              num: 0,
              price: 0,
              pic: '../pics/xilanhuachaorou.png',
              isVip: false,
              vipPrice: 0,
              notVip: true,
              isChoseType: false,
              isAddShopCar: true,
              isDelShopCar: true,
              isShowZero: false
            },
            {
              id: 18,
              name: '麻香手撕鸡',
              sale: '5670',
              num: 0,
              price: 0,
              pic: '../pics/tudouniurou.png',
              isVip: false,
              vipPrice: 0,
              notVip: true,
              isChoseType: false,
              isAddShopCar: true,
              isDelShopCar: true,
              isShowZero: false
            },
            {
              id: 19,
              name: '热狗',
              sale: '2272',
              num: 0,
              price: 0,
              pic: '../pics/tudouniurou.png',
              isVip: false,
              vipPrice: 0,
              notVip: true,
              isChoseType: false,
              isAddShopCar: true,
              isDelShopCar: true,
              isShowZero: false
            },
            {
              id: 20,
              name: '土豆肉丝',
              sale: '1308',
              num: 0,
              price: 0,
              pic: '../pics/tudouniurou.png',
              isVip: false,
              vipPrice: 0,
              notVip: true,
              isChoseType: false,
              isAddShopCar: true,
              isDelShopCar: true,
              isShowZero: false
            },
            {
              id: 21,
              name: '豆角炒肉',
              sale: '1979',
              num: 0,
              price: 0,
              pic: '../pics/tudouniurou.png',
              isVip: false,
              vipPrice: 0,
              notVip: true,
              isChoseType: false,
              isAddShopCar: true,
              isDelShopCar: true,
              isShowZero: false
            },
            {
              id: 22,
              name: '脆皮烧鸭',
              sale: '4710',
              num: 0,
              price: 0,
              pic: '../pics/xilanhuachaorou.png',
              isVip: false,
              vipPrice: 0,
              notVip: true,
              isChoseType: false,
              isAddShopCar: true,
              isDelShopCar: true,
              isShowZero: false
            },
            {
              id: 23,
              name: '腐竹肉丝',
              sale: '4897',
              num: 0,
              price: 0,
              pic: '../pics/tudouniurou.png',
              isVip: false,
              vipPrice: 0,
              notVip: true,
              isChoseType: false,
              isAddShopCar: true,
              isDelShopCar: true,
              isShowZero: false
            },
          ],
          menuArr2: [{
              name: '巴西烤肉套餐',
              sale: '448',
              num: 0,
              price: 13,
              pic: '../pics/taocan.png',
              isVip: false,
              vipPrice: 0,
              notVip: true,
              isChoseType: false,
              isAddShopCar: true,
              isDelShopCar: true,
              isShowZero: false
            },
            {
              name: '黄金板栗鸡套餐',
              sale: '209',
              num: 0,
              price: 13,
              pic: '../pics/taocan.png',
              isVip: false,
              vipPrice: 0,
              notVip: true,
              isChoseType: false,
              isAddShopCar: true,
              isDelShopCar: true,
              isShowZero: false
            },
          ],
        })
        // 输出结果
       // console.log(JSON.stringify(res, null, 2))
        fn(res);
    }
}
module.exports = {
    ajax: ajax
}